version: '3.8'

services:
  pg:
    image: postgres:12
    command:
      - 'postgres'
      - '-c'
      - 'max_connections=100'
      - '-c'
      - 'shared_buffers=256MB'
    environment:
      POSTGRES_PASSWORD: canduma
    ports:
      - 5432:5432
